language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - android-28
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-23
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
env:
  global:
   # install timeout in minutes (2 minutes by default)
   - ANDROID_TARGET=android-27
   - ANDROID_ABI=armeabi-v7a


# Run assemble, unit tests, and create coverage report
script:
 - ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck

  after_success:
    - bash <(curl -s https://codecov.io/bash)
#  - ./gradlew clean assembleDebug assembleRelease testDebug createDebugUnitTestCoverageReport
#  # Renaming folder and files of reports so codecov.io can find it
#  - mv app/build/reports/jacoco/createDebugUnitTestCoverageReport app/build/reports/jacoco/jacocoTestDebugUnitTestReport
#  - mv app/build/reports/jacoco/jacocoTestDebugUnitTestReport/createDebugUnitTestCoverageReport.xml app/build/reports/jacoco/jacocoTestDebugUnitTestReport/jacocoTestDebugUnitTestReport.xml
#  # Codecov.io
#  - bash <(curl -s https://codecov.io/bash)